spring:
  datasource:
    url: "jdbc:mysql://localhost/suburb_manager"
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  
  hateoas:
     use-hal-as-default-json-media-type: false

  hibernate: 
    dialect: "org.hibernate.dialect.MySQL5Dialect" 
     
server:
  port: 8080
  
