spring:
  datasource:
    initialize: false
    url: "jdbc:mysql://localhost/suburb_manager"
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      
  hibernate: 
    dialect: "org.hibernate.dialect.MySQL5Dialect" 
     
server:
  port: 8080
  
